apiVersion: v1
kind: Pod
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Chart.Name }}
  labels: 
    app: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  containers:
  - name: nginx
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    env:
    resources:
      requests:
        memory: {{ .Values.resources.memory }}
        cpu: {{ .Values.resources.cpu }}
      limits:
        memory: {{ .Values.resources.limits.memory }}
        cpu: {{ .Values.resources.limits.cpu }}
