
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    name: redis 
    ports: 
    - containerPort: {{ .Values.port }}
